# Generated by Django 5.2.9 on 2025-12-06 22:56

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recaudacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de recaudación')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto recaudado')),
                ('numero_semana', models.PositiveIntegerField(blank=True, verbose_name='Semana')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['fecha'], name='finanzas_ap_fecha_ca9f46_idx'), models.Index(fields=['numero_semana'], name='finanzas_ap_numero__c3af3c_idx')],
            },
        ),
    ]
