# Generated by Django 5.2.9 on 2025-12-07 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recaudacion',
            options={'ordering': ['-fecha'], 'verbose_name': 'Recaudación', 'verbose_name_plural': 'Recaudaciones'},
        ),
    ]
